version: '3.3'
services:
  backend:
    build:
      context: .
    command: ${COMMAND:-tail -f /dev/null}
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./config/database.docker.yml:/app/config/database.yml
  db:
    image: postgres:13.3
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: mdzpwd
      POSTGRES_USER: mdz
volumes:
  db_data:
